export const cityArray = [
  { value: "Aguilares", label: "Aguilares" },
  { value: "Apopa", label: "Apopa" },
  { value: "Ayutuxtepeque", label: "Ayutuxtepeque" },
  { value: "Ciudad Delgado", label: "Ciudad Delgado" },
  { value: "Cuscatancingo", label: "Cuscatancingo" },
  { value: "El Paisnal", label: "El Paisnal" },
  { value: "Guazapa", label: "Guazapa" },
  { value: "Ilopango", label: "Ilopango" },
  { value: "Mejicanos", label: "Mejicanos" },
  { value: "Nejapa", label: "Nejapa" },
  { value: "Panchimalco", label: "Panchimalco" },
  { value: "Rosario de Mora", label: "Rosario de Mora" },
  { value: "San Marcos", label: "San Marcos" },
  { value: "San Martín", label: "San Martín" },
  { value: "San Salvador", label: "San Salvador" },
  { value: "Santiago Texacuangos", label: "Santiago Texacuangos" },
  { value: "Santo Tomás", label: "Santo Tomás" },
  { value: "Soyapango", label: "Soyapango" },
  { value: "Tonacatepeque", label: "Tonacatepeque" },
];
